dashboard/product/urls.py
from django.urls import path
from . import views
from dashboard.decorators import user_dashboard_permission 

app_name = 'product_dashboard'

urlpatterns = [
    path('create/', user_dashboard_permission(views.CreateProduct.as_view()),
         name= 'product_create'),
    
    path('update/<int:pk>/', user_dashboard_permission(views.UpdateProduct.as_view()),
         name= 'product_update'),
    
    path('list/', views.ListProduct.as_view(),
         name= 'product_list'),
    
    path('<int:pk>/list/images/', views.ProductImageList.as_view(),
         name= 'product_image_list'),
    
    path('<int:pk>/create/image/', user_dashboard_permission(views.create_image),
         name= 'create_image'),


    path('delete/image/<int:pk>', user_dashboard_permission(views.delete_image),
         name= 'delete_image'),
    
    path('delete/<int:pk>', user_dashboard_permission(views.delete_product),
         name= 'delete_product'),
    
    
]

groceryshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

from . import settings

urlpatterns = [
    path('', lambda req: redirect('/accounts/login/')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('products/', include('product.urls', namespace='products')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('order/', include('order.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

order/urls.py
from django.urls import path
from .views import DetailOrder, ListOrder

app_name = 'order'
urlpatterns = [
    path('<int:pk>/', DetailOrder.as_view(), name="detail_order"),
    path('', ListOrder.as_view(), name="list_order"),
]

product/urls.py
from django.urls import path

from .views import detail_product, add_product_to_checkout, ListProduct, ListProductBrand

app_name = "products"

urlpatterns = [
    path('<str:slug>/', detail_product,name="detail_product"),
    path('category/<str:slug>/', ListProduct.as_view(),name="list_product"),
    path('brand/<str:slug>/', ListProductBrand.as_view(),name="list_product_brand"),
    path('add/<int:pk>/', add_product_to_checkout, name="add_product_to_checkout"),
    
]

product/models.py
from django.db import models
from django.urls import reverse, reverse_lazy
from django.utils.text import slugify
from mptt.managers import TreeManager
from mptt.models import MPTTModel
from django_countries.fields import CountryField
import uuid

fields = ["name", "description", "background_image"]

# Create your models here.
class Category(MPTTModel):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField()
    background_image = models.ImageField(upload_to = 'category_background', 
                                         blank = True, null = True
    )
    parent = models.ForeignKey(
        'self', 
        blank = True,
        null = True, 
        on_delete = models.CASCADE
    )
    
    tree = TreeManager()
    
    def __str__(self):
        return self.name
    
    
    def get_absolute_url(self):
        return reverse_lazy("dashboard:category_dashboard:category_list") 
    
# First
class Brand(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    image = models.ImageField(blank = True)
    country = CountryField(blank = True)
    
    def get_absolute_url(self):
        return reverse_lazy("dashboard:brand_dashboard:create_brand")
    def __str__(self):
        return self.name
    
class Product(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField(default = '')
    price = models.FloatField(default=0)
    weight = models.FloatField(default = 1)
    # sku needs more work
    sku = models.UUIDField(default = uuid.uuid4, unique = True, editable = True)
    stock = models.PositiveIntegerField(default = 5)
    brand = models.ForeignKey('Brand',on_delete= models.CASCADE, null = True)
    category = models.ForeignKey('Category',on_delete= models.CASCADE, null = True)
    
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse_lazy("dashboard:product_dashboard:product_list")
    
    def get_thumbnail(self):
        return self.productimage_set.first() 

# name - image url - price - brand
    
class ProductImage(models.Model):
    # image = models.ImageField(blank = True)
    image_url = models.URLField(blank = True)
    product = models.ForeignKey('Product', on_delete = models.CASCADE)
    alt = models.CharField(max_length = 225)
    

dashboard/product/forms.py
from django import forms 
from product.models import ProductImage
from django_countries.fields import CountryField
from product.models import Brand

class ProductImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        exclude = ('product','alt')
        
          
class FilterForm(forms.Form):
    min_price = forms.FloatField(label='Min Price', required=False)
    max_price = forms.FloatField(label='Max Price', required=False)
    brand_Nationality = CountryField(blank_label='Any Nationality', blank=True).formfield()
    brand_name = forms.CharField(required = False, label = 'Brand Name')
    

    brand_name_choice = forms.ModelChoiceField(label = 'Brand Name Choice',queryset= Brand.objects.all(),
                                               widget = forms.Select, empty_label= "All Brands",
                                               to_field_name = 'name',required=False)
    
    product_name = forms.CharField(required = False, label = 'Product Name')

    

dashboard/product/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import JsonResponse
from django.utils.text import slugify
from django.views.generic import CreateView, UpdateView, ListView
from product.models import Product,ProductImage, Category
from order.models import OrderLine
from django.shortcuts import get_object_or_404, render
from .forms import ProductImageForm
from django.urls import reverse
from .forms import FilterForm
from django.db.models import Count
from math import inf


class CreateProduct(CreateView):
    model = Product
    template_name = "dashboard/product/create.html"
    fields = ["name", 'description', 'price', 'weight', 'sku', 
              'stock', 'brand', 'category']
    
    def form_valid(self, form):
        instance = form.save()
        instance.slug = slugify(instance.name) + "-" + str(instance.id)
        instance.save()
        
        return super(CreateProduct, self).form_valid(form)
    

class UpdateProduct(UpdateView):
    model = Product
    template_name = "dashboard/product/create.html"
    fields = ["name", 'description', 'price', 'weight', 'sku', 
              'stock', 'brand', 'category']

    
    def form_valid(self, form):
        instance = form.instance
        instance.slug = slugify(instance.name) + "-" + str(instance.id)
        instance.save()
        
        return super(UpdateProduct, self).form_valid(form)
    
class ListProduct(ListView):
    model = Product
    template_name = "dashboard/product/list.html"
    paginate_by = 12
    context_object_name = "product_list"

    def get_queryset(self):
        queryset = super().get_queryset()


        # Filter queryset based on price if form data is present
        best_sellers = self.request.GET.get('submit_action') == 'best_sellers'
        
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')
        if (min_price != '' and min_price is not None) or (max_price != '' and max_price is not None):
            
            if min_price == '' or min_price is None:
                min_price = 0
            
            if max_price == '' or max_price is None:
                max_price = inf
        
            queryset = queryset.filter(price__gte=min_price, price__lte=max_price)
            
        
        # based on brand nationality
        brand_Nationality = self.request.GET.get('brand_Nationality')
        if brand_Nationality != '' and brand_Nationality is not None:
            queryset = queryset.filter(brand__country__iexact = brand_Nationality)
        
        
        # based on brand name
        brand_name = (self.request.GET.get('brand_name'))            
        if brand_name != '' and brand_name is not None:
            brand_name = brand_name.lower()
            queryset = queryset.filter(brand__name__icontains = brand_name)
        
        
        # based on brand name choice
        brand_name_choice = (self.request.GET.get('brand_name_choice'))
        if brand_name_choice != '' and brand_name_choice is not None:
            brand_name_choice = brand_name_choice.lower()            
            queryset = queryset.filter(brand__name__iexact = brand_name_choice)
        
        
        # based on product name
        product_name = (self.request.GET.get('product_name'))            
        if product_name != '' and product_name is not None:
            product_name = product_name.lower()
            queryset = queryset.filter(name__icontains = product_name)
        
        if best_sellers:
            queryset = queryset.annotate(orders_count = Count('orderlines'))
            queryset = queryset.order_by("-orders_count", "name")
        else:
            queryset = queryset.order_by("name")
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Pass the form to the template
        context['filter_form'] = FilterForm(self.request.GET)

        return context
    
    
    
class ProductImageList(ListView):
    model = ProductImage
    template_name = 'dashboard/product/list_images.html'    
    

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductImageList, self).get_context_data(**kwargs)
        context['form'] = ProductImageForm()
        context['product_id'] = self.kwargs.get('pk')
        return context
    
    def get_queryset(self):
        return super(ProductImageList, self).get_queryset().filter(product__id=self.kwargs.get('pk'))
    
def create_image(request, pk):
    product = get_object_or_404(Product, pk=pk)
    form = ProductImageForm(request.POST, request.FILES)
    if form.is_valid():
        obj = form.save(commit = False)
        obj.product = product
        obj.alt = product.name
        obj.save()
        return JsonResponse({
            'message':'product image successfully created','alt' : obj.alt,
            'url': obj.image.url,
            'delete_url': reverse('dashboard:product_dashboard:delete_image',kwargs={
                                 'pk': obj.pk})}, 
            status = 200)
    
    return JsonResponse({'message':form.errors}, status = 400)

def delete_image(request,pk):
    product_image = get_object_or_404(ProductImage,pk=pk) 
    if product_image:
        product_image.delete()
        return JsonResponse({'message' : 'the image has been deleted successfully'},status=200)
    
    return JsonResponse({'message':'this product image instance does not exist'}, status=400)

def delete_product(request,pk):
    product = get_object_or_404(Product,pk=pk) 
    if product:
        product.delete()
        return JsonResponse({'message' : 'the product has been deleted successfully'},status=200)
    
    return JsonResponse({'message':'this product instance does not exist'}, status=400)

product/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404,render
from django.views.generic import ListView, DetailView
from .models import Product, Category, Brand
from order.models import Order, OrderLine
from checkout.form import CheckoutLineForm
from checkout.models import CheckoutLine, Checkout
from django.http import HttpResponseRedirect
from django.urls import reverse
from datetime import timedelta
from django.utils import timezone


def detail_product(request, slug, form = None):
    product = get_object_or_404(Product, slug=slug)
    if not form:
        form = CheckoutLineForm(request.POST or None, product = product)
    total_users = OrderLine.objects.filter(product=product)
    
    twenty_four_hours_ago = timezone.now() - timedelta(days = 1)
    users_last_24 = total_users.filter(order__created__gte=twenty_four_hours_ago)
    context = {
        'form':form,
        'object':product,
        'users_total': total_users.count(), #
        'users_last_24': users_last_24.count() #
    }
    return render(request,'product/detail.html', context)
        

class ListProduct(ListView):
    model = Product
    template_name = 'product/list.html'  
    paginate_by = 12
    
    def get_queryset(self):
        category = get_object_or_404(Category, slug = self.kwargs.get('slug'))
        categories = category.get_descendants(include_self=True)
        qs = super(ListProduct,self).get_queryset().filter(
            category__in=categories
        ).order_by('name')
        
        return qs
class ListProductBrand(ListView):
    model = Product
    template_name = 'product/list.html'  
    paginate_by = 12
    
    def get_queryset(self):
        brand = get_object_or_404(Brand, slug = self.kwargs.get('slug'))
        qs = super(ListProductBrand,self).get_queryset().filter(
            brand__exact= brand
        ).order_by('name')
        
        return qs
    
def get_or_create_checkout(request, checkout_queryset = Checkout.objects.all()):
    user = request.user
    if user.is_authenticated:
        
        return checkout_queryset.get_or_create(
            user = user,
            email = user.email
        )[0]
        
    token = request.get_signed_cookie('checkout', default = None)
    return checkout_queryset.filter(token = token, user = None).get_or_create(
        user = None
    )[0]
        
 
def set_checkout_cookie(checkout,response):
    max_age = int(timedelta(days=30).total_seconds())
    response.set_signed_cookie('checkout', checkout.token, max_age=max_age)
    
    
def add_product_to_checkout(request, pk):
    product = get_object_or_404(Product, pk = pk)
    if request.method == "POST":
        checkout = get_or_create_checkout(request)
        instance = CheckoutLine(product=product, checkout=checkout)
        form = CheckoutLineForm(request.POST, instance=instance, product=product)
        
        if form.is_valid():
            checkout_line = CheckoutLine.objects.filter(
                product=product,
                checkout=checkout
            )
            if checkout_line.exists():
                instance = checkout_line[0]
                instance.quantity += int(request.POST.get('quantity'))
                instance.save()
            
            else:            
                form.save()                 
            
            # Changed Here   
            response = HttpResponseRedirect(reverse('checkout:checkout_index'))
            
        else:
            response = detail_product(request,product.slug,form)
            
        if not request.user.is_authenticated:
            set_checkout_cookie(checkout, response)
            
        return response
    return HttpResponseRedirect(reverse('checkout:checkout_index'))

templates/product/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="custom-heading"> {{ object.name }}</h1>
    
    <div id="carouselExampleIndicators" class="carousel slide">
        <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            {% for image in object.productimage_set.all %}
                <div class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}">
                    <img src="{{ image.image_url }}" class="d-block w-100" alt="{{ image.alt }}">
                </div>
            {% endfor %}
            {% comment %} <div class="carousel-item">
                <img src="https://images-eu.ssl-images-amazon.com/images/I/71oyM0epm4L._AC_UL600_SR600,400_.jpg" class="d-block w-100" alt="bla">
            </div> {% endcomment %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
        </button>
    </div>
    <div class="container">
        <ul class="list-group">
            <li class="list-group-item">Price: {{ object.price }}</li>
            <li class="list-group-item">Weight: {{ object.weight }}</li>
            <li class="list-group-item">
                Brand: <a href="{% url "products:list_product_brand" slug=object.brand.slug %}">{{ object.brand }}</a>
            </li>
            <li class="list-group-item">SKU: {{ object.sku }}</li>
            <li class="list-group-item">Description: {{ object.description }}</li>
          </ul>
    
        <form action = "{% url 'products:add_product_to_checkout' pk=object.pk %}" method = "post" class="form-container">
            {% csrf_token %}
            {{ form.as_p }}
            <button class = "btn btn-outline-success">Add To Cart</button>
        </form>

        <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Count of users who bought this item:
            <span class="badge bg-primary rounded-pill">{{ users_total }}</span></li>
        <li class="list-group-item d-flex justify-content-between align-items-center">Count of users who bought this item in the last 24 hours: <span class="badge bg-primary rounded-pill">{{ users_last_24 }}</span></li>
        </ul>
    </div>
    
{% endblock %}

templates/product/list.html
{% extends 'base.html' %}


{% block content %}
    <div class="pagination">
        {% if is_paginated %}  
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-dark" href="?page={{ page_obj.previous_page_number }}"><b>Previous</b></a>
            {% endif %}
            <span>
                <b>Page: {{ page_obj.number }} out of {{ page_obj.paginator.num_pages }}</b> 
            </span>
            {% if page_obj.has_next %}
                <a class="btn btn-outline-dark" href="?page={{ page_obj.next_page_number }}"><b>Next</b></a>
            {% endif %}
        {% endif %}
    </div>

    <div class="row row-cols-1 row-cols-md-4 g-1">
        {% for object in object_list %}
        <div class="col">
        <div class="card" style="width:18rem;">
            <div class="btn btn-outline-success">
            <a style="text-decoration:none" class="card-body" href="{% url 'products:detail_product' slug=object.slug%}">
                <p class="text-center">
                <img class="card-img-top" src="{{ object.get_thumbnail.image_url }}" alt="{{ object.get_thumbnail.alt }}">
                </p>
                <h5>{{ object.name }}</h5>
                <h5>EGP {{ object.price }}</h5>
            </a>
            </div>
        </div>
    </div>
        {% endfor %}
    </div>
    <div class="pagination">
        {% if is_paginated %}  
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-dark" href="?page={{ page_obj.previous_page_number }}"><b>Previous</b></a>
            {% endif %}
            <span>
                <b>Page: {{ page_obj.number }} out of {{ page_obj.paginator.num_pages }}</b> 
            </span>
            {% if page_obj.has_next %}
                <a class="btn btn-outline-dark" href="?page={{ page_obj.next_page_number }}"><b>Next</b></a>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}