checkout/urls.py
from django.urls import path
from .views import checkout_view,create_shipping_address, edit_shipping_address, create_order_view
from .views import delete_item
from dashboard.decorators import user_dashboard_permission 

app_name = "checkout"
urlpatterns = [
    path('',checkout_view, name="checkout_index"),
    path('create/address/', create_shipping_address, name="checkout_create_address"),
    path('edit/address/', edit_shipping_address, name="checkout_edit_address"),
    path('create/order/', create_order_view, name="create_order_view"),
    path('delete/<int:pk>', delete_item, name= 'delete_item'),    
]

dashboard/urls.py
from django.urls import path, include
from .category import urls as category_url
from .product import urls as product_url
from .brand import urls as brand_url
from .views import index
app_name = "dashboard"

urlpatterns = [
    path('index/', index, name="index"),
    path('category/', include(category_url, namespace = 'category_dashboard')),
    path('product/', include(product_url, namespace = 'product_dashboard')),
    path('brand/', include(brand_url, namespace = 'brand_dashboard')),
    
]

groceryshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

from . import settings

urlpatterns = [
    path('', lambda req: redirect('/accounts/login/')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('products/', include('product.urls', namespace='products')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('order/', include('order.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

order/urls.py
from django.urls import path
from .views import DetailOrder, ListOrder

app_name = 'order'
urlpatterns = [
    path('<int:pk>/', DetailOrder.as_view(), name="detail_order"),
    path('', ListOrder.as_view(), name="list_order"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Grocery app </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block static %}
    {% endblock %}
</head>

<body>
<nav class="navbar">
    <a class="btn btn-outline-primary" href="{% url 'dashboard:index' %}">Home</a>
    <a class="btn btn-outline-secondary" href="{% url 'dashboard:product_dashboard:product_list'%}">Products</a>
    <a class="btn btn-outline-secondary" href="{% url 'dashboard:category_dashboard:category_list'%}">Categories</a>
    <a class="btn btn-outline-secondary" href="{% url 'dashboard:brand_dashboard:list_brand'%}">Brand</a>
    <a class="btn btn-outline-secondary" href="{% url 'dashboard:index' %}">Orders</a>
    {% block search %}
    {% endblock %}
    <a class="btn btn-outline-success" href="{% url 'checkout:checkout_index' %}">Cart</a>
    <a class="btn btn-danger" href="{% url 'account_logout' %}">Logout</a>
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasExampleLabel">Search and Filter</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <div>
            <form action="{% url 'dashboard:product_dashboard:product_list' %}" method="get" class="form-container">
              {% csrf_token %}
              {{ filter_form.as_p }}
              <button class = "btn btn-outline-success" type="submit" name="submit_action" value="search">Search or Filter</button>
              <button class = "btn btn-outline-success" type="submit" name="submit_action" value="best_sellers">Best Sellers</button>
            </form>        
          </div>
        </div>
    </div>
</nav>
<hr>

  


{% block content %}

{% endblock content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
</script>

{% block js%} 
<script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
{% endblock %}
<script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/pages.html
{% extends "base.html" %}

{% block content %}

{% endblock %} 
{% block paging %}
<div class="pagination">
    {% if is_paginated %}  
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-dark" href="?page={{ page_obj.previous_page_number }}"><b>Previous</b></a>
        {% endif %}
        <span>
            <b>Page: {{ page_obj.number }} out of {{ page_obj.paginator.num_pages }}</b> 
        </span>
        {% if page_obj.has_next %}
            <a class="btn btn-outline-dark" href="?page={{ page_obj.next_page_number }}"><b>Next</b></a>
        {% endif %}
    {% endif %}
</div>
{% endblock %}