checkout/urls.py
from django.urls import path
from .views import checkout_view,create_shipping_address, edit_shipping_address, create_order_view
from .views import delete_item
from dashboard.decorators import user_dashboard_permission 

app_name = "checkout"
urlpatterns = [
    path('',checkout_view, name="checkout_index"),
    path('create/address/', create_shipping_address, name="checkout_create_address"),
    path('edit/address/', edit_shipping_address, name="checkout_edit_address"),
    path('create/order/', create_order_view, name="create_order_view"),
    path('delete/<int:pk>', delete_item, name= 'delete_item'),    
]

groceryshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

from . import settings

urlpatterns = [
    path('', lambda req: redirect('/accounts/login/')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('products/', include('product.urls', namespace='products')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('order/', include('order.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

order/urls.py
from django.urls import path
from .views import DetailOrder, ListOrder

app_name = 'order'
urlpatterns = [
    path('<int:pk>/', DetailOrder.as_view(), name="detail_order"),
    path('', ListOrder.as_view(), name="list_order"),
]

checkout/models.py
from django.db import models
from django.contrib.auth import get_user_model
from uuid import uuid4


# Create your models here.

class Checkout(models.Model):
    created = models.DateTimeField(auto_now_add=True)

    user = models.ForeignKey(
        get_user_model(),
        on_delete = models.CASCADE, 
        blank= True,
        null = True, 
    )
    
    email = models.EmailField()
    token = models.UUIDField(
        primary_key = True,
        default = uuid4,
        editable = False    
    )
    
    note = models.TextField()
    
    #shipping not shipping_id
    shipping = models.ForeignKey('userprofile.Addresses',on_delete = models.CASCADE, blank= True, null=True)
    
    def __str__(self):
        return str(self.token)
    
    

class CheckoutLine(models.Model):
    checkout = models.ForeignKey(
        'Checkout', on_delete=models.CASCADE
    )
    
    product = models.ForeignKey(
        'product.Product', on_delete=models.CASCADE
    )
    
    quantity = models.PositiveIntegerField()
    
    def __str__(self):
        return self.product.name
    
    
    def get_sub_total(self):
        return round(self.product.price * self.quantity, 2)
    
    

checkout/views.py
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from .models import Checkout, CheckoutLine
from userprofile.form import ShippingAddressForm, VisitorShippingAddressForm, EditShippingAddress
from userprofile.models import UserProfile, Addresses
from django.urls import reverse
from order.models import Order, OrderLine
from .decorator import user_cookie_checkout
from product.models import Product
from .form import PaymentCardForm
from random import randint
from django.utils import timezone
from datetime import datetime, timedelta

def get_checkout(request):
    user = request.user
    if user.is_authenticated:
        return Checkout.objects.get(user=user, email=user.email)
    
    token = request.get_signed_cookie('checkout')
    return Checkout.objects.get(user=None, token=token)


def checkout_view(request):
    is_none = False
    total = 0
    try:
        checkout = get_checkout(request)
        checkout_line = checkout.checkoutline_set.all()
        for line in checkout_line:
            total += line.get_sub_total()
            
    except Checkout.DoesNotExist:
        is_none = True


    user = request.user
    if (not user.is_authenticated and request.get_signed_cookie('checkout', None) is None) or is_none:
        context = {
            'checkout_line':None
        }
        return TemplateResponse(request,'checkout/index.html', context)
    context ={
        'checkout_line': CheckoutLine.objects.filter(checkout=checkout),
        'checkout': checkout,
        'total' : round(total, 2)
    }
    return TemplateResponse(request, 'checkout/index.html', context)

@user_cookie_checkout
def create_shipping_address(request):
    checkout = get_checkout(request)
    user = request.user
    is_auth = user.is_authenticated
    if is_auth:
        form = ShippingAddressForm(request.POST or None)
    else:
        form = VisitorShippingAddressForm(request.POST or None, instance=checkout.shipping)
    context = {
        'form': form
    }
    if request.method == "POST":
        if form.is_valid():
            obj = form.save()
            if is_auth:
                profile = get_object_or_404(UserProfile, user=user)
                profile.user_addresses.add(obj)
                profile.save()
            else:
                checkout.email = request.POST.get('email')
            checkout.shipping = obj
            checkout.save()
            return HttpResponseRedirect(reverse('checkout:create_order_view'))
    else:
        if is_auth:
            addresses_form = EditShippingAddress(user=user)
            context.update({
                'addresses_form' : addresses_form,
            })
        
    return TemplateResponse(request, 'checkout/shipping_create.html', context)

@user_cookie_checkout
def edit_shipping_address(request):
    user = request.user
    
    if user.is_authenticated and request.method == "POST":
        form = EditShippingAddress(request.POST, user=user)
        if form.is_valid():
            checkout = get_checkout(request)
            checkout.shipping = Addresses.objects.get(id=int(request.POST.get('addresses')))
            checkout.save()
            return HttpResponseRedirect(reverse('checkout:create_order_view'))
    
    return HttpResponseRedirect(reverse('checkout:create_order_view'))
    
@user_cookie_checkout
def create_order_view(request):
    user = request.user
    checkout = get_checkout(request)
    checkout_line = checkout.checkoutline_set.all()
    total = 0

    if checkout_line.count() > 0:
        for line in checkout_line: 
            total += line.get_sub_total()
    total = round(total, 2)
    if request.method == "POST":
        if checkout_line.count() > 0:
            form = PaymentCardForm(request.POST)
            
            if not form.is_valid():
                context = {
                    'checkout_line': checkout_line,
                    'checkout': checkout,
                    'total': total,
                    'form': form
                }
                return TemplateResponse(request, 'checkout/confirm_order.html', context)
            
            if user.is_authenticated:
                order = Order.objects.create(checkout_token=checkout.token, user=user, 
                                             email=user.email, shipping=checkout.shipping, total=total)
                
            else:
                order = Order.objects.create(checkout_token=checkout.token, email=checkout.email, 
                                               shipping=checkout.shipping, total=total)
            
            # print("-"*20)

            for line in checkout_line:
                product = line.product
                order_line = OrderLine.objects.create(order=order, product=product, 
                                        product_name=product.name, product_price=product.price, 
                                        sku=product.sku, quantity=line.quantity)
                
                # total += order_line.get_sub_total()
                Product.objects.filter(sku=product.sku).update(stock=product.stock-line.quantity)
                # real_product.
            
            order.total = total
            order.save()
            checkout.delete()
            response = HttpResponseRedirect(reverse('order:detail_order', kwargs={
                'pk': order.pk,    
            }))
            response.delete_cookie('checkout', None)
            return response
    
    form = PaymentCardForm()
    
    context = {
        'checkout_line': checkout_line,
        'checkout': checkout,
        'total': total,
        'form': form
    }
    return TemplateResponse(request, 'checkout/confirm_order.html', context)


def delete_item(request,pk):
    item = get_object_or_404(CheckoutLine,pk=pk) 
    if item:
        item.delete()
        return checkout_view(request)
        # return JsonResponse({'message' : 'the item has been deleted successfully from cart'},status=200)
    
    return JsonResponse({'message':'this item is not your card'}, status=400)

templates/checkout/confirm_order.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            {% if checkout_line %}
                {% for line in checkout_line %}
                    <div class="col-md-12">
                        <p>{{ line }} [{{ line.product.sku }}]</p>
                        <p>{{ line.quantity  }} x {{ line.product.price }}$</p>
                        <p>subtotal: {{ line.get_sub_total }}</p>
                        <hr> 
                    </div>
                {% endfor %}
                <p> total : {{total}} </p>
            {% endif %}
            <form action="{% url 'checkout:create_order_view' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Buy Now</button> 
            </form>
            
            {% comment %} <form action="{% url 'checkout:create_order_view' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="lucky" value="true">
                <button type="submit" class="btn btn-success">I'm Feeling Lucky</button> 
            </form> {% endcomment %}
        </div>
    </div>
{% endblock %}

templates/checkout/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            {% if checkout_line %}
                {% for line in checkout_line %}
                    <div class="col-md-12">
                        <p>{{ line }} [{{ line.product.sku }}]</p>
                        
                        <p>{{ line.quantity  }} x {{ line.product.price }}$</p>

                        <p>subtotal: {{ line.get_sub_total }}</p>
                        
                        <a class="btn btn-outline-danger" href="{% url 'checkout:delete_item' pk=line.pk  %}">Delete Item</a>


                        <hr> 
                    </div>
                {% endfor %}
                <p>total: {{ total }}</p>

                <a class="btn btn-primary" href="{% url 'checkout:checkout_create_address' %}">Next</a>
                <p></p>
                <a class="btn btn-primary" href="{% url 'dashboard:product_dashboard:product_list' %}">Back to products</a>

            {% else %}
                <h1>Please add some products to your shopping cart.<h1>
                <h1>Place some orders!</h1>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/checkout/shipping_create.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h4> Please create a shipping address </h4>
            <form action="{% url 'checkout:checkout_create_address' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    Create a shipping address
                </button>
            </form>
        </div>
        <div class="col-md-6">
            {% if addresses_form %}
                <h4>Select a shipping address</h4>
                <form action="{% url 'checkout:checkout_edit_address' %}" method="post">
                    {% csrf_token %}
                    {{ addresses_form.as_p }}
                    <button type="submit" class="btn btn-primary">Select Shipping Address</button>
                </form>
            {% endif %}

        </div>
    </div> 
{% endblock %}