groceryshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

from . import settings

urlpatterns = [
    path('', lambda req: redirect('/accounts/login/')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('products/', include('product.urls', namespace='products')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('order/', include('order.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

order/urls.py
from django.urls import path
from .views import DetailOrder, ListOrder

app_name = 'order'
urlpatterns = [
    path('<int:pk>/', DetailOrder.as_view(), name="detail_order"),
    path('', ListOrder.as_view(), name="list_order"),
]

order/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.

order_status = ((0, "Fullfield"), (1, "Unfullfield"), (2, "Canceled"), (3, "Refunded"))

class Order(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=order_status, default=0)
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    email = models.EmailField()
    checkout_token = models.CharField(max_length=36, default="")
    note = models.TextField(blank=True, default="")
    shipping = models.ForeignKey('userprofile.Addresses',on_delete = models.CASCADE)
    total = models.FloatField()
    
    def __str__(self):
        return self.email
    
    
class OrderLine(models.Model):
    order = models.ForeignKey(
        Order, on_delete = models.CASCADE,
        #editable=False,
        related_name = "orderlines", #
    )
    
    product = models.ForeignKey(
        'product.Product', 
        on_delete =  models.SET_NULL,
        blank = True,
        null = True,
        related_name = "orderlines"
    )
    
    product_name = models.CharField(max_length = 255)
    product_price = models.FloatField()
    sku = models.CharField(max_length = 50)
    quantity = models.PositiveIntegerField()
    
    def __str__(self):
        return f"{self.product_name}x{self.product_price}"
    
    def get_sub_total(self):
        return round(self.product_price * self.quantity, 2)
    

order/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from .models import Order, OrderLine
from django.views.generic import DetailView, ListView

# Create your views here.
class DetailOrder(DetailView):
    paginate_by = 12
    model = Order
    template_name = 'order/detail.html'
    
    
class ListOrder(ListView):
    model = Order
    template_name = 'order/list.html'
    paginate_by = 12
    
    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            return super(ListOrder, self).get_queryset().filter(user=user, email=user.email)

templates/order/detail.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <table>
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                </tr>
                {% for foo in object.orderlines.all %} 
                        <tr>
                        {% comment %} <td> {{ foo }} </td> {% endcomment %}
                        <td>{{ foo.product }} [{{ foo.sku }}]</td>
                        <td>{{ foo.product_price }}</td>
                        <td>{{ foo.quantity }}</td>
                        <td>{{ foo.get_sub_total }}</td>
                    {% empty %}
                        <h1>empty</h1>
                    </tr>
                {% endfor %}
                <tr>
                <td>Total</td>
                <td></td>
                <td></td>
                <td>{{ object.total }}</td>
                </tr>
            </table>
        </div> 
    </div> 
{% endblock  %}

templates/order/list.html
{% extends "base.html" %}

{% block content %}
    {% for foo in object_list %}
        <div>
            <a href="{% url 'order:detail_order' pk=object.pk %}">
                {{ foo.email }} | {{ foo.total }}$
            </a>
        </div>
    {% endfor %}
{% endblock  %}